[package]
name = "wakectl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }

chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.9"

serde = { version = "1", features = ["derive"] }

toml = "0.8"

anyhow = "1"

directories = "5"
constcat = "0.6.1"
